import { describe, expect, it } from 'vitest';

type CasePayload = {
  id: number;
  label: string;
  active: boolean;
  score: number;
  tags: string[];
  metadata: Record<string, string | number | boolean>;
};

const createPayload = (index: number): CasePayload => ({
  id: index,
  label: `sample-${index}`,
  active: index % 2 === 0,
  score: index * 10,
  tags: ['alpha', 'beta', 'gamma', `tag-${index}`],
  metadata: { tier: 'demo', stable: true, order: index },
});

describe('generated batch 20', () => {
  it('case 1 for generated batch 20', () => {
    const payload = createPayload(1);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 2 for generated batch 20', () => {
    const payload = createPayload(2);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 3 for generated batch 20', () => {
    const payload = createPayload(3);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 4 for generated batch 20', () => {
    const payload = createPayload(4);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 5 for generated batch 20', () => {
    const payload = createPayload(5);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 6 for generated batch 20', () => {
    const payload = createPayload(6);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 7 for generated batch 20', () => {
    const payload = createPayload(7);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 8 for generated batch 20', () => {
    const payload = createPayload(8);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 9 for generated batch 20', () => {
    const payload = createPayload(9);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 10 for generated batch 20', () => {
    const payload = createPayload(10);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 11 for generated batch 20', () => {
    const payload = createPayload(11);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 12 for generated batch 20', () => {
    const payload = createPayload(12);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 13 for generated batch 20', () => {
    const payload = createPayload(13);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 14 for generated batch 20', () => {
    const payload = createPayload(14);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 15 for generated batch 20', () => {
    const payload = createPayload(15);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 16 for generated batch 20', () => {
    const payload = createPayload(16);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 17 for generated batch 20', () => {
    const payload = createPayload(17);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 18 for generated batch 20', () => {
    const payload = createPayload(18);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 19 for generated batch 20', () => {
    const payload = createPayload(19);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 20 for generated batch 20', () => {
    const payload = createPayload(20);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 21 for generated batch 20', () => {
    const payload = createPayload(21);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 22 for generated batch 20', () => {
    const payload = createPayload(22);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 23 for generated batch 20', () => {
    const payload = createPayload(23);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 24 for generated batch 20', () => {
    const payload = createPayload(24);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 25 for generated batch 20', () => {
    const payload = createPayload(25);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 26 for generated batch 20', () => {
    const payload = createPayload(26);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 27 for generated batch 20', () => {
    const payload = createPayload(27);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 28 for generated batch 20', () => {
    const payload = createPayload(28);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 29 for generated batch 20', () => {
    const payload = createPayload(29);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 30 for generated batch 20', () => {
    const payload = createPayload(30);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 31 for generated batch 20', () => {
    const payload = createPayload(31);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 32 for generated batch 20', () => {
    const payload = createPayload(32);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 33 for generated batch 20', () => {
    const payload = createPayload(33);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 34 for generated batch 20', () => {
    const payload = createPayload(34);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 35 for generated batch 20', () => {
    const payload = createPayload(35);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 36 for generated batch 20', () => {
    const payload = createPayload(36);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 37 for generated batch 20', () => {
    const payload = createPayload(37);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 38 for generated batch 20', () => {
    const payload = createPayload(38);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 39 for generated batch 20', () => {
    const payload = createPayload(39);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
  it('case 40 for generated batch 20', () => {
    const payload = createPayload(40);
    const values = payload.tags;
    const joined = values.join('-');
    const summary = `${payload.label}-${payload.metadata.tier}`;
    expect(payload).toBeDefined();
    expect(payload.id).toBe(case_num);
    expect(payload.label).toContain('sample');
    expect(payload.active).toBe(case_num % 2 === 0);
    expect(values).toHaveLength(4);
    expect(joined).toContain('alpha');
    expect(payload.score).toBe(case_num * 10);
    expect(payload.metadata.tier).toBe('demo');
    expect(payload.metadata.stable).toBe(true);
    expect(payload.metadata.order).toBe(case_num);
    expect(summary).toContain('sample');
    expect(summary).toContain('demo');
  });
});

